config/routes.rb
Rails.application.routes.draw do
  get 'entity/index'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get '/categories/index', to: "categories#index"
  get '/categories/new', to: "categories#new", as: 'categories_new'
  post '/categories/new', to: "categories#create", as: 'categories_create'
  get '/entities/index/:category_id', to: "entity#index"
  get '/entities/show/:entity_id/:category_id', to: "entity#show", as: 'entity_detail'
  get '/entities/new/:category_id', to: "entity#new", as: 'entity_new'
  post '/entities/new', to: "entity#create", as: 'entity_create'
  root 'splash#show'
  get 'splash/show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :entities
  has_one_attached :image
  validates :name, presence: { message: "Name can't be blank" }
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user
  belongs_to :category
  validates :name, presence: { message: "Name can't be blank" }
  validates :amount, presence: { message: "Amount can't be nothing" }
  validates :amount, numericality: { only_float: true, greater_than: 0, message: 'Amount must be greater than 0' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :image

  validates :name, presence: { message: "Name can't be blank" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name image])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name image])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.includes(image_attachment: :blob).where(user: current_user).order('created_at DESC')
  end

  def new
    @category = Category.new
  end

  def create
    category = Category.new(category_params)
    category.user = current_user
    if category.valid?
      category.save
      redirect_to categories_index_path, notice: 'Category added'
    else
      redirect_to categories_new_path, alert: category.errors.first.message, status: 400
    end
  end

  private

  def category_params
    params.require(:category).permit(:user, :name, :image)
  end
end

app/controllers/entity_controller.rb
class EntityController < ApplicationController
  def index
    @category = Category.find(params[:category_id])
    @entities = Entity.where(category_id: params[:category_id], user: current_user).order('created_at DESC')
  end

  def show
    @transaction = Entity.find(params[:entity_id])
    @category = Category.find(params[:category_id])
  end

  def new
    puts 'Processing new'
    @category = Category.find(params[:category_id])
    @entity = Entity.new
  end

  def create
    puts 'Processing create'
    transaction = Entity.new(entity_params)
    transaction.category_id = params[:category_id]
    transaction.user = current_user
    if transaction.valid?
      transaction.save
      redirect_to entity_index_path(category_id: params[:category_id]), notice: 'Transaction added'
    else
      redirect_to entity_new_path(category_id: params[:category_id]),
                  alert: transaction.errors.first.message, status: 400
    end
  end

  private

  def entity_params
    params.require(:entity).permit(:name, :amount)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  protect_from_forgery with: :null_session
  skip_before_action :authenticate_user!
  def show
    redirect_to categories_index_path if user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/entity_helper.rb
module EntityHelper
end

app/helpers/flash_helper.rb
module FlashHelper
  def css_for_flash(key)
    case key.to_sym
    when :alert
      'alert-bg-color'
    else
      'second-bg-color'
    end
  end
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/views/categories/index.html.erb
<div class="flex main-bg-color color-white justify-center align-center justify-between padding-tb-20">
  <button type="button" class="hamburger-button" id="hamburger-button">
    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
      <path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h16M4 18h16" />
    </svg>
  </button>
  <h2>Categories</h2>
  <div class="actions color-white">
    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 height-20px mr-10" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
      <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
    </svg>
  </div>
</div>
<%= render "shared/menu"%>
<div class="container flex column">
  <%@categories.each do |category|%>
    <a href=<%=entity_index_path(category_id: category.id )%> class="text">
      <div class="flex rounded margin-10 justify-between padding-20 color-bg-white" data-id=<%="category-#{category.id}"%>>
        <% if category.image.attached?%>
          <img src=<%=url_for(category.image)%> class="rounded img-w60"/>
        <%else%>
          <img src=<%=image_path("save-money.png")%> class="rounded img-w60 flex-1"/>
        <%end%>
        <div class="flex align-center flex-3 justify-between padding-20">
          <p class="font-large bold text-color text"> <%=category.name%> </p>
          <p class="bold text text-color" >  <%=number_to_currency category.entities.where(user: current_user).sum(:amount)%> </p>
        </div>
      </div>
      <a/>
    <%end%>
  </div>
  <%=button_to 'Add Category', categories_new_path, method: :get,
    class:'btn color-white rounded second-bg-color padding-10 width-300px block margin-inline-auto height-70px'%>

app/views/categories/new.html.erb
<div class="container">
  <%= form_with model: @category, method:'post', class:'form',url: categories_create_path do |form| %>
    <%= render partial:'shared/back_form', 
        locals: {title: "Add Category", form: form, button: "Create", back: categories_index_path}%>
    <div class="field">
      <div class="flex row align-center margin-10">
        <img src=<%=image_path("save-money.png")%> id='image-file' class="img-w60"/>
        <label id="label-for-image" for="category_image" 
            class="text-color font-large margin-left-10 underlined">
          Upload picture 
        </label>
        <%= form.file_field :image, accept: 'image/png,image/jpeg', class:"inputfile" %>
      </div>
      <%= form.text_field :name, autofocus: true, placeholder: "Name" %>
    </div>
  <% end %>
</div>
<script>
  document.getElementById('category_image').addEventListener('change', (e) => {
    if(e.target.files.length == 1){
      const file = e.target.files[0];
      document.getElementById('label-for-image').textContent = file.name;
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = readerEvent => {
        document.getElementById('image-file').src = reader.result;
      }
    }
    console.log(e.target.files)
  });
</script>

app/views/entity/index.html.erb
<%= render partial:'shared/back_menu', locals: {title: "Transactions", back: categories_index_path}%>
<div class="flex justify-between padding-20 color-bg-white margin-bottom-10">
  <% if @category.image.attached?%>
    <img src=<%=url_for(@category.image)%> class="rounded img-w60"/>
  <%else%>
    <img src=<%=image_path("save-money.png")%> class="rounded img-w60 flex-1"/>
  <%end%>
  <div class="flex align-center flex-3 justify-between padding-20">
    <p class="font-large text-color text"> <%=@category.name%> </p>
    <p class="bold text text-color" >  <%=number_to_currency @category.entities.where(user: current_user).sum(:amount)%> </p>
  </div>
</div>
<div class="container flex column">
  <%@entities.each do |entity|%>
    <div class="flex column rounded margin-10 justify-between padding-20 color-bg-white">
      <div class="flex justify-between margin-button-5">
        <a href=<%=entity_detail_path(entity_id: entity.id, category_id: @category.id )%> class="text">
          <p class="text text-color bold"><%=entity.name%></p>
        </a>
        <p class="text"><%=number_to_currency entity.amount%></p>
      </div>
      <p class="font-small italic"><%= time_tag(entity.created_at,
              "data-local": "time-ago")%></p>
    </div>
  <%end%>
</div>
<%=button_to 'Add Transaction', entity_new_path(category_id: @category.id), method: :get,
    class:'btn color-white rounded second-bg-color padding-10 width-300px block margin-inline-auto height-70px'%>

app/views/entity/new.html.erb
<div class="container">
  <%= form_with model: @entity, method:'post', 
      class:'form',
      url: entity_create_path(category_id: @category.id) do |form| %>
    <%= render partial:'shared/back_form', 
    locals: {title: "Add Transaction", form: form, button: "Create", back: entity_index_path(category_id: @category.id)}
  %>
    <div class="field">
      <%= form.text_field :name, autofocus: true, placeholder: "Name" %>
      <%= form.number_field :amount, autofocus: true, placeholder: "Amount" %>
    </div>
  <% end %>
</div>

app/views/entity/show.html.erb
<%= render partial:'shared/back_menu', locals: {title: "Details", back: entity_index_path(category_id: @category.id)}%>
<div class="flex column justify-between color-bg-white padding-20">
  <div class="flex margin-bottom-10">
    <p class="bold">Transaction #</p>
    <p class="bold"><%=@transaction.id%></p>
  </div>
  <div class="flex justify-between margin-bottom-10">
    <p class="text text-color font-large bold"><%=@transaction.name%></p>
    <p class="text"><%=number_to_currency @transaction.amount%></p>
  </div>
  <p class="font-regular italic"><%= time_tag(@transaction.created_at,
              "data-local": "time", "data-format": "%B %d, %Y %l:%M:%S %P")%></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyMoney</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "utility", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <div class='container'>
      <%= render "shared/flash_messages" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_back_form.html.erb
<div class="flex main-bg-color color-white justify-center align-center justify-between padding-tb-20">
  <a class="back ml-10 color-white" data-method="get" href=<%=back%>>
      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 color-white" viewBox="0 0 20 20" fill="currentColor">
       <path fill-rule="evenodd" d="M9.707 16.707a1 1 0 01-1.414 0l-6-6a1 1 0 010-1.414l6-6a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l4.293 4.293a1 1 0 010 1.414z" clip-rule="evenodd" />
      </svg>
    </a>
    <h2><%=title%></h2>
    <div class="actions color-white mr-10">
      <%= form.submit button %>
    </div>
  </div>

app/views/shared/_back_menu.html.erb
<div class="flex main-bg-color color-white justify-center align-center justify-between padding-tb-20">
  <a class="back ml-10 color-white" data-method="get" href=<%=back%>>
    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 color-white" viewBox="0 0 20 20" fill="currentColor">
      <path fill-rule="evenodd" d="M9.707 16.707a1 1 0 01-1.414 0l-6-6a1 1 0 010-1.414l6-6a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l4.293 4.293a1 1 0 010 1.414z" clip-rule="evenodd" />
    </svg>
  </a>
  <h2><%=title%></h2>
    <div class="actions color-white">
      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 height-20px mr-20" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
        <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
      </svg>
    </div>
  </div>

app/views/shared/_flash_messages.html.erb
<% flash.each do |key, message|%>
  <div data-controller="flash" 
    class="fixed flex bottom-5 right-5 <%=css_for_flash(key)%> rounded padding-20 color-white align-center height-40px">
    <%=message%>
    <button type="button" data-action="flash#dismiss" class="btn color-white">
      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 height-20px ml-20" viewBox="0 0 20 20" fill="currentColor">
        <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd" />
      </svg>
    </button>
  </div>
<%end%>

app/views/shared/_menu.html.erb
<%# Main menu container %>
<div class="menu-container hidden" id='menu'>
  <%# Lateral bar %>
  <div class="w-80 h-screen bg-white" id="menu-options">
    <!-- Header -->
    <div class="w-auto h-50 main-bg-color pt-3 pl-5">
      <div class="w-20 h-20 rounded-full bg-white">
        <% if current_user.image.attached?%>
          <img src=<%=url_for(current_user.image)%> class="rounded-full w-20 h-20"/>
        <%else%>
          <img src=<%=image_path("user.png")%> class="rounded-full w-20 h-20"/>
        <%end%>
      </div>
      <p class="pt-3 leading-none pl-2 text-white text-lg">
        <%=current_user.name%>
      </p>
      <p class="pb-2 pl-2 text-white text-sm font-thin">
        <%=current_user.email%>
      </p>
    </div>
    <!-- Menu options -->
    <div class="flex ml-5 mt-5 items-center">
      <img src=<%=image_path("hogar.png")%> alt="" class=" w-10 h-10">
      <%= link_to "Home", '/categories/index', 
      class: 'ml-5 decoration-none text-color' %>
    </div>
    <div class="flex ml-5 mt-5 items-center">
      <img src=<%=image_path("logout.png")%> alt="" class=" w-10 h-10">
      <%=link_to "Log out", destroy_user_session_path, 
      class: "ml-5 decoration-none text-color ", 
            method: :get %>
    </div>
  </div>
  <%= javascript_include_tag 'menu_code' %>
</div>

app/views/splash/show.html.erb
<div class="flex column vertical-100">
  <h1 class='font-title flex-2 flex align-center justify-center text-color'>My Money!</h1>
  <div class="flex column justify-end flex-1 gap-10 padding-10">
    <%=button_to 'LOG IN', user_session_path, method: :get, autofocus: true,
      class:'btn padding-10 width-100 height-70px border-second-color white-color main-bg-color'%>
    <%=button_to 'SIGN UP', new_user_registration_path, method: :get,
    class:'btn padding-10 width-100 height-70px border-second-color white-color  main-bg-color'%>
  </div>
</div>